version: '3'
services:
  schooleduapp-postgresql:
    container_name: schooleduapp-postgresql
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=schooleduapp
    ports:
      - "5432:5432"
    restart: always

#  app:
#    build: .
#    volumes:
#      - .:/app
#      - ~/.m2:/root/.m2
#    working_dir: /app
#    command: mvn clean spring-boot:run
#    depends_on:
#    - schooleduapp-postgresql